Repository zextras/carbonio-tasks-ce, pull requests merged in 2024-03, with the labels that each got.

#31 fix: make the service re-throws runtime exception in the Boot class
  boot/src/main/java/com/zextras/carbonio/tasks/Boot.java
Labels: bug

#33 ci: add timestamp in the artifact pkgrel
  Jenkinsfile
  boot/pom.xml
  core/pom.xml
  package/PKGBUILD
  pom.xml
Labels: ci

#32 feat: add Flyway to manage database migrations
  .pre-commit-config.yaml
  boot/pom.xml
  boot/src/main/java/com/zextras/carbonio/tasks/Boot.java
  core/pom.xml
  core/src/main/java/com/zextras/carbonio/tasks/Constants.java
  core/src/main/java/com/zextras/carbonio/tasks/config/TasksConfig.java
  core/src/main/java/com/zextras/carbonio/tasks/config/TasksModule.java
  core/src/main/java/com/zextras/carbonio/tasks/config/providers/FlywayProvider.java
  core/src/main/java/com/zextras/carbonio/tasks/config/providers/UserManagementClientProvider.java
  core/src/main/java/com/zextras/carbonio/tasks/dal/DatabaseInitializer.java
  core/src/main/java/com/zextras/carbonio/tasks/dal/DatabaseManager.java
  core/src/main/java/com/zextras/carbonio/tasks/dal/dao/DbInfo.java
  core/src/main/java/com/zextras/carbonio/tasks/dal/impl/DatabaseManagerFlyway.java
  core/src/main/java/com/zextras/carbonio/tasks/dal/repositories/DbInfoRepository.java
  core/src/main/java/com/zextras/carbonio/tasks/dal/repositories/impl/DbInfoRepositoryEbean.java
  core/src/main/java/com/zextras/carbonio/tasks/rest/services/HealthService.java
  core/src/main/resources/db/migration/V1__init.sql
  core/src/main/resources/db/migration/V2__remove-dbinfo.sql
  core/src/test/java-it/com/zextras/carbonio/tasks/Simulator.java
  core/src/test/java-it/com/zextras/carbonio/tasks/dal/DatabaseConnectionManagerIT.java
  core/src/test/java-it/com/zextras/carbonio/tasks/dal/DatabaseInitializerIT.java
  core/src/test/java-ut/com/zextras/carbonio/tasks/config/TaskConfigTest.java
  core/src/test/java-ut/com/zextras/carbonio/tasks/dal/DatabaseInitializerTest.java
  core/src/test/java-ut/com/zextras/carbonio/tasks/dal/DatabaseManagerFlywayTest.java
  core/src/test/java-ut/com/zextras/carbonio/tasks/dal/dao/DbInfoTest.java
  core/src/test/java-ut/com/zextras/carbonio/tasks/dal/repositories/impl/DbInfoRepositoryEbeanTest.java
  pom.xml
Labels: enhancement
